import { existsSync, writeFileSync, unlinkSync, mkdirSync, readFileSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'

const REGISTRY_URL   = 'https://registry.npmjs.org/buildflow-dev/latest'
const UPDATE_FILE    = '.buildflow/core/UPDATE.md'
const REGISTRY_PATH  = join(homedir(), '.buildflow', 'projects.json')

function getProjectRegistry() {
  try { return JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')) } catch { return [] }
}

function allProjectPaths() {
  const projects = getProjectRegistry()
  const cwd = process.cwd()
  if (!projects.includes(cwd) && existsSync(join(cwd, '.buildflow'))) {
    projects.push(cwd)
  }
  return projects.filter(p => existsSync(join(p, '.buildflow', 'core')))
}

export async function checkVersion(currentVersion) {
  try {
    const res = await fetch(REGISTRY_URL, {
      signal: AbortSignal.timeout(3000),
      headers: { Accept: 'application/json' },
    })
    if (!res.ok) return null

    const { version: latest } = await res.json()

    if (latest === currentVersion) {
      // Clear stale notices from all registered projects
      for (const p of allProjectPaths()) {
        const f = join(p, UPDATE_FILE)
        if (existsSync(f)) unlinkSync(f)
      }
      return null
    }

    // Write UPDATE.md to every registered project so their next AI session
    // shows the update notice regardless of which project is opened.
    const notice = buildUpdateNotice(currentVersion, latest)
    for (const p of allProjectPaths()) {
      try {
        writeFileSync(join(p, UPDATE_FILE), notice)
      } catch {}
    }

    return { current: currentVersion, latest }
  } catch {
    return null  // Network timeout or offline — silently skip
  }
}

export function clearUpdateNotice() {
  // Clear from all registered projects, not just cwd
  for (const p of allProjectPaths()) {
    try {
      const f = join(p, UPDATE_FILE)
      if (existsSync(f)) unlinkSync(f)
    } catch {}
  }
}

function buildUpdateNotice(current, latest) {
  return `# BuildFlow Update Available

> A new version of BuildFlow is available.
> Your AI tool detected this file at session start.

| | Version |
|---|---|
| **Installed** | ${current} |
| **Latest** | ${latest} |

## How to Update

Run this in your terminal:

\`\`\`bash
npx buildflow-dev update
\`\`\`

Or if installed globally:

\`\`\`bash
npm install -g buildflow-dev@latest
\`\`\`

After updating, this notice will disappear automatically.

---
*Generated by BuildFlow CLI · ${new Date().toISOString().split('T')[0]}*
`
}
