import { existsSync, writeFileSync, unlinkSync, mkdirSync } from 'fs'
import { join } from 'path'

const REGISTRY_URL = 'https://registry.npmjs.org/buildflow-dev/latest'
const UPDATE_FILE  = '.buildflow/core/UPDATE.md'

export async function checkVersion(currentVersion) {
  try {
    const res = await fetch(REGISTRY_URL, {
      signal: AbortSignal.timeout(3000),
      headers: { Accept: 'application/json' },
    })
    if (!res.ok) return null

    const { version: latest } = await res.json()
    const updatePath = join(process.cwd(), UPDATE_FILE)

    if (latest === currentVersion) {
      // Remove stale notice if we're already up to date
      if (existsSync(updatePath)) unlinkSync(updatePath)
      return null
    }

    // Only write the file if .buildflow/ exists (i.e. project is initialized)
    const coreDir = join(process.cwd(), '.buildflow', 'core')
    if (!existsSync(coreDir)) return { current: currentVersion, latest }

    mkdirSync(coreDir, { recursive: true })
    writeFileSync(updatePath, buildUpdateNotice(currentVersion, latest))

    return { current: currentVersion, latest }
  } catch {
    return null  // Network timeout or offline — silently skip
  }
}

export function clearUpdateNotice() {
  const updatePath = join(process.cwd(), UPDATE_FILE)
  if (existsSync(updatePath)) unlinkSync(updatePath)
}

function buildUpdateNotice(current, latest) {
  return `# BuildFlow Update Available

> A new version of BuildFlow is available.
> Your AI tool detected this file at session start.

| | Version |
|---|---|
| **Installed** | ${current} |
| **Latest** | ${latest} |

## How to Update

Run this in your terminal:

\`\`\`bash
npx buildflow-dev update
\`\`\`

Or if installed globally:

\`\`\`bash
npm install -g buildflow-dev@latest
\`\`\`

After updating, this notice will disappear automatically.

---
*Generated by BuildFlow CLI · ${new Date().toISOString().split('T')[0]}*
`
}
